[package]
name = "opengate"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
dasp = { version = "0.11.0", features = ["signal"] }
hound = "3.5.1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
